[build]
builder = "NIXPACKS"
buildCommand = "pip install -r requirements.txt"

[[services]]
name = "feishu-bot"
startCommand = "python feishu_bot.py"
healthcheckPath = "/webhook"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "mcp-weather"
startCommand = "python weather1.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
PORT = "8080"
PYTHON_VERSION = "3.9" 
